-- noinspection SqlNoDataSourceInspectionForFile
SELECT id,
ARRAY_AGG(DISTINCT g ) AS txt_g,
MIN(type) AS type,
ARRAY_AGG(DISTINCT name) AS name,
ARRAY_AGG(DISTINCT name) AS txt_name,
MIN(description ) AS description,
ARRAY_AGG(DISTINCT description ) AS txt_description,
ARRAY_AGG(DISTINCT contenturl ) AS txt_distribution,
ARRAY_AGG(DISTINCT url ) AS txt_url,
ARRAY_AGG(DISTINCT temporalCoverage ) AS txt_temporalCoverage,
ARRAY_AGG(DISTINCT keywords ) AS txt_keywords,
ARRAY_AGG(DISTINCT courseName ) AS txt_courseName,
ARRAY_AGG(DISTINCT location ) AS txt_location,
ARRAY_AGG(DISTINCT iritype ) AS txt_iritype,
ARRAY_AGG(DISTINCT wkt ) AS txt_wkt,
MIN(DISTINCT geom ) AS txt_geom,
MIN(DISTINCT lat )  AS txt_lat,
MIN(DISTINCT long )  AS txt_long,
ARRAY_AGG(DISTINCT place_name ) AS txt_place_name,
MIN(DISTINCT datePublished ) AS txt_datePublished,
MIN(DISTINCT dateModified ) AS txt_dateModified,
FROM arrow_table
GROUP BY id
