PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <https://schema.org/>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>

SELECT DISTINCT (?s as ?id) ?g ?type ?name ?description ?keywords
    ?contenturl ?courseName ?url
    ?location ?iritype ?wkt ?geom ?lat ?long ?place_name
    ?temporalCoverage ?datePublished ?dateModified
    ?sameAs ?citation ?license ?version ?includedInDataCatalog ?memberOf
    ?parentOrganization ?knowsAbout ?affiliation ?category
    ?vehicleConfiguration ?vehicleSpecialUsage
    ?jobTitle ?knowsLanguage ?educationalCredentialAwarded ?author
    ?hasCourseInstance ?location ?areaServed ?startDate ?endDate

WHERE {
    {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:name ?name .
            ?s schema:description ?description .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:keywords ?keywords .
            FILTER (!isIRI(?keywords) && !isBlank(?keywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:distribution ?distribution .
            ?distribution schema:contentUrl ?contenturl .
            FILTER (!isIRI(?keywords) && !isBlank(?keywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:keywords ?irikeywords .
            ?irikeywords a schema:DefinedTerm .
            ?irikeywords schema:name ?keywords .
            FILTER (isIRI(?irikeywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:keywords ?keywords .
            FILTER (!isIRI(?keywords) && !isBlank(?keywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:keywords ?irikeywords .
            ?irikeywords a schema:DefinedTerm .
            ?irikeywords schema:name ?keywords .
            FILTER (isIRI(?irikeywords))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:url ?url .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:location ?location .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:address ?address .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Course> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:hasCourseInstance ?hasCourseInstance .
            ?hasCourseInstance schema:name ?courseName
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:name ?place_name .
            FILTER (!isIRI(?place_name)) .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:latitude ?lat .
            ?sc schema:longitude ?long .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:geo ?geo .
            ?geo a ?geotype .
            ?geo ?geompred ?geom .
            FILTER (!isIRI(?geom))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/Dataset> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s geosparql:hasGeometry ?hasgeom .
            ?hasgeom geosparql:asWKT ?wkt
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:latitude ?lat .
            ?sc schema:longitude ?long .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)

        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s schema:spatialCoverage ?sc .
            ?sc a schema:Place .
            ?sc schema:geo ?geo .
            ?geo a ?geotype .
            ?geo ?geompred ?geom .
            FILTER (!isIRI(?geom))
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)

        }
    } UNION {
        graph ?g {
            BIND(<https://schema.org/DataCatalog> AS ?iritype)
            ?s rdf:type ?iritype .
            ?s geosparql:hasGeometry ?hasgeom .
            ?hasgeom geosparql:asWKT ?wkt
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)

        }
    } UNION {
        graph ?g {
            ?s rdf:type ?iritype .
            ?s schema:temporalCoverage ?temporalCoverage .
            BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
        }
    } UNION {
        SELECT ?s ?type ?dateModified
        WHERE {
            graph ?g {
                ?s rdf:type ?iritype .
                ?s schema:dateModified ?dateModified
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
        LIMIT 1
    } UNION {
        SELECT ?s ?type ?datePublished
        WHERE {
            graph ?g {
                ?s rdf:type ?iritype .
                ?s schema:datePublished ?datePublished .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
        LIMIT 1
    } UNION {
        SELECT ?s ?type ?sameAs
        WHERE {
            graph ?g {
                ?s rdf:type ?iritype .
                ?s schema:sameAs ?sameAs .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?type ?license
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Dataset> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:license ?license .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?type ?citation
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Dataset> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:citation ?citation .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?type ?version
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Dataset> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:version ?version .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?type ?includedInDataCatalog
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Dataset> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:includedInDataCatalog ?includedInDataCatalog .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?type ?memberOf
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Person> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:memberOf ?memberOf .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?parentOrganization
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Organization> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:parentOrganization ?parentOrganization .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)

            }
        }
    } UNION {
        SELECT ?s ?knowsAbout
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Person> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:knowsAbout ?knowsAbout .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?affiliation
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Person> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:affiliation ?affiliation .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?category
        WHERE {
            graph ?g {
                ?s rdf:type ?iritype .
                ?s schema:category ?category .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?vehicleConfiguration
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Vehicle> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:vehicleConfiguration ?vehicleConfiguration .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?vehicleSpecialUsage
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Vehicle> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:vehicleSpecialUsage ?vehicleSpecialUsage .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?jobTitle
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Person> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:jobTitle ?jobTitle .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?knowsLanguage
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Person> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:knowsLanguage ?knowsLanguage .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?educationalCredentialAwarded
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Person> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:educationalCredentialAwarded ?educationalCredentialAwarded .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?author
        WHERE {
            graph ?g {
                ?s rdf:type ?iritype .
                ?s schema:author ?author .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?hasCourseInstance
        WHERE {
            graph ?g {
                BIND(<https://schema.org/Course> AS ?iritype)
                ?s rdf:type ?iritype .
                ?s schema:hasCourseInstance ?hasCourseInstance .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?areaServed
        WHERE {
            graph ?g {
                ?s rdf:type ?iritype .
                ?s schema:areaServed ?areaServed .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?startDate
        WHERE {
            graph ?g {
                ?s rdf:type ?iritype .
                ?s schema:startDate ?startDate .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    } UNION {
        SELECT ?s ?endDate
        WHERE {
            graph ?g {
                ?s rdf:type ?iritype .
                ?s schema:endDate ?endDate .
                BIND(REPLACE(STR(?iritype), "https://schema.org/", "") AS ?type)
            }
        }
    }
}
