# Development config file for ODIS nodes, that drives the Dagster pipeline
# to update the ODIS graph.  Other important notes about this config file:
#  - sorted alphabetically by 'name' parameter
#  - no need to use quotes. Use the single-quoted style (') if characters 
#    such as " and \ are being used inside the string to avoid escaping them
#  - pid: should point to the ODISCat 'view' if available, such as https://catalogue.odis.org/view/689
#         or if not, use format: https://oceaninfohub.org/.well-known/org/[name]
#  - url: point to sitemap or sitegraph
#  - changefreq: how often sitemap is updated
#  - dateadded: YYYY-MM-DD (the date that JSON-LD became available, but not
#               necessarily when it was included in the ODIS graph)
#  - headless: false if JSON-LD is embedded in page, or if sitegraph
#  - cron: how often to harvest the endpoint, defaults to weekly (on Sunday)
#  - active: ready to include in ODIS
#  - if a parameter has no value, leave blank (with no quotes)
# To validate at commandline: execute the following (if the file contains valid 
# yaml, it will return nothing) :
#    python -c 'import yaml, sys; yaml.safe_load(sys.stdin)' < sources.yaml
sources:
  #
  # British Oceanographic Data Centre
  #
  - name: bodc
    propername: British Oceanographic Data Centre (BODC)
    catalogue: https://www.bodc.ac.uk/data/bodc_database/nodb/search/
    domain: https://www.bodc.ac.uk/
    logo: https://www.bodc.ac.uk/assets/img/bodc-logo-colour-white.png
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/bodc
    sourcetype: sitemap
    url: https://api.linked-systems.uk/sitemap_pap_api.xml
    changefreq: monthly
    backend: Custom
    headless: false
    dateadded: 2023-07-10
    cron: 0 7 * * 0 
    active: true
  #
  # Canary Current Large Marine Ecosystem (CCLME)
  #
  - name: cclme
    propername: Canary Current Large Marine Ecosystem (CCLME)
    catalogue: https://www.fao.org/in-action/canary-current-lme/en
    domain: https://www.fao.org/in-action/canary-current-lme/en
    logo: https://www.fao.org/images/corporatelibraries/fao-logo/fao-logo-en.svg?sfvrsn=f64522b4_36
    pid: https://catalogue.odis.org/view/3276
    sourcetype: sitemap
    url: http://www.ideo-cclme.ieo.es/odis/odis_sitemap.xml
    changefreq: monthly
    backend: Custom
    headless: false
    dateadded: 2023-10-30
    cron: 0 2 * * 0
    active: true
  #
  # CIOOS Atlantic
  #    
  # - name: cioosatlantic
  #   propername: CIOOS Atlantic
  #   catalogue: https://catalogue.cioosatlantic.ca/
  #   domain: https://cioosatlantic.ca
  #   logo: https://cioosatlantic.ca/wp-content/themes/cioos-siooc-wordpress-theme/img/atlantic/cioos-atlantic_EN.svg?x79655
  #   #missing ODISCat entry
  #   pid: https://oceaninfohub.org/.well-known/org/cioosatlantic
  #   sourcetype: sitemap
  #   url: https://catalogue.cioosatlantic.ca/sitemap/sitemap.xml
  #   #url: https://catalogue.cioosatlantic.ca/sitemap/sitemap-1.xml
  #   changefreq: as needed
  #   backend: CKAN  
  #   headless: false
  #   dateadded: 2022-06-04
  #   active: true
  #
  # INVEMAR Geospatial
  #
  - name: invemargeo
    propername: Latin America and the Caribbean Region (LAC) Geospatial
    catalogue: https://portete.invemar.org.co/chm/
    domain: https://portete.invemar.org.co
    logo: https://www.invemar.org.co/o/invemar-actual-theme/images/logoWebINVEMAR.png
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/invemarvessels
    sourcetype: sitegraph
    url: https://portete.invemar.org.co/chm/api/oih/platformgeo?format=json
    changefreq:
    backend: INVEMAR CHM
    headless: false
    dateadded: 2023-08-22
    cron: 0 8 * * 0 
    active: true
  #
  # Marine Institute Data Catalogue
  #    
  #
  - name: marineie
    propername: Marine Institute Data Catalogue (Ireland)
    catalogue: https://data.marine.ie/geonetwork/srv/eng/catalog.search
    domain: https://data.marine.ie
    logo: https://data.marine.ie/geonetwork/images/logos/494b5d66-a774-4a7e-86f0-c860cc21331b.png
    pid: https://catalogue.odis.org/view/193
    sourcetype: sitemap
    url: https://data.marine.ie/geonetwork/srv/api/sitemap
    changefreq: daily
    backend: GeoNetwork
    headless: false
    dateadded: 2023-08-22
    cron: 0 9 * * 0 
    active: true
  #
  # NCEI Marine Microplastics Catalogue
  #    
  #
  - name: ncei
    propername: NCEI Marine Microplastics Catalogue
    catalogue: https://experience.arcgis.com/experience/b296879cc1984fda833a8acc93e31476 
    domain: https://www.ncei.noaa.gov/products/microplastics
    logo: https://www.ncei.noaa.gov/themes/custom/ncei/logo.svg
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/ncei 
    sourcetype: sitemap
    url: https://raw.githubusercontent.com/iodepo/odis-arch/master/collection/tempHosting/data-ncei/sitemap.xml
    changefreq: monthly
    backend: ArcGIS
    headless: false
    dateadded: 2024-01-24
    cron: 0 2 * * 0 
    active: true    
  #
  # ODIS Catalogue
  #
  - name: odiscat
    propername: ODIS Catalogue (ODISCat)
    catalogue: https://catalogue.odis.org/
    domain: https://odis.org/
    logo: https://gatewaygeomatics.com/dl/odis/odis-catalogue-logo.png
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/odiscat
    sourcetype: sitemap
    url: https://stag.catalogue.odis.org/sitemapIndex.xml
    changefreq: daily
    backend: Custom
    headless: false
    dateadded: 2023-10-19
    cron: 0 11 * * 0 
    active: true
  #
  # Aquatic Sciences and Fisheries Abstracts (OpenASFA)
  #
  - name: openasfa
    propername: Aquatic Sciences and Fisheries Abstracts (OpenASFA)
    catalogue: https://www.fao.org/fishery/en/openasfa
    domain: https://www.fao.org/fishery/en
    logo: https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/FAO_logo.svg/180px-FAO_logo.svg.png
    pid: https://catalogue.odis.org/view/3277
    sourcetype: sitemap
    url: https://www.fao.org/fishery/sitemap/fishery_openasfa_en.xml
    #url: https://www.fao.org/fishery/sitemap.xml
    changefreq: monthly
    backend: Custom
    headless: false
    dateadded: 2024-02-02
    cron: 0 11 * * 0 
    active: true    
  #
  # Observing System Monitoring Center
  #
  - name: osmc
    propername: Observing System Monitoring Center (OSMC)
    catalogue: https://osmc.noaa.gov/erddap/info/index.html
    domain: https://www.osmc.noaa.gov/
    logo: https://www.osmc.noaa.gov/OSMC_logo.png
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/osmc
    sourcetype: sitemap
    url: https://osmc.noaa.gov/erddap/sitemap.xml
    changefreq: monthly
    backend: Custom
    headless: false
    dateadded: 2023-10-12
    cron: 0 10 * * 0 
    active: true    
  #
  # POGO
  # 
  - name: pogo
    propername: Partnership for Observation of the Global Ocean (POGO)
    catalogue: https://pogo-ocean.org/
    domain: https://geoblueplanet.org/
    logo: https://pogo-ocean.org/wp-content/uploads/2020/02/POGO1_long-01-768x135.png
    pid: https://catalogue.odis.org/view/3247
    sourcetype: sitemap
    url: https://pogo-ocean.org/pogo-member-sitemap.xml
    changefreq: as needed  
    backend: WordPress  
    headless: false
    dateadded: 2022-11-30
    active: false
  #
  # UNEP Data Catalogue (also referred to as "WESR" or "GEMS Ocean")
  # 
  - name: unep
    propername: UNEP Data Catalogue
    catalogue: https://datacatalog.unep.org/app 
    domain: https://www.unep.org/
    logo: https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/UNEP_logo.svg/195px-UNEP_logo.svg.png
    pid: https://catalogue.odis.org/view/3288
    sourcetype: sitemap
    url: https://datacatalog.unep.org/en/oceans_sitemap.xml
    changefreq: monthly 
    backend: CKAN  
    headless: false
    dateadded: 2024-01-22
    active: true    
  #
  # VLIZ: Flanders Marine Institute catalogue
  #   note: VLIZ & EMODNet services were unified in late 2022 
  # - name: vliz
  #   propername: VLIZ - Flanders Marine Institute catalogue
  #   catalogue: https://emodnet.ec.europa.eu/geonetwork/srv/eng/catalog.search#/home
  #   domain: http://www.vliz.be/en 
  #   logo: ""
  #   #missing ODISCat entry
  #   pid: https://oceaninfohub.org/.well-known/org/vliz
  #   sourcetype: sitegraph
  #   url: https://raw.githubusercontent.com/iodepo/odis-arch/master/collection/tempHosting/data-vliz/vliz-simple-graph.json
  #   backend: GeoNetwork  
  #   headless: false
  #   dateadded: 2022-08-03
  #   active: false
  #
  # WIO Symphony
  # 
  - name: wiosymphony
    propername: WIO (Western Indian Ocean) Symphony
    catalogue: https://symphony.nairobiconvention.org/login
    domain: https://www.nairobiconvention.org/wio-symphony/
    logo: https://www.nairobiconvention.org/wp-content/uploads/2019/05/nairobic_logo.png
    pid: https://catalogue.odis.org/view/3290
    sourcetype: sitemap
    url: https://raw.githubusercontent.com/WIOSymphony/wiosym/main/metadata/sitemap.xml
    changefreq: monthly 
    backend: Custom  
    headless: false
    dateadded: 2024-01-24
    active: true  
  #
  # Leibniz Center for Tropical Marine Research (ZMT)
  # 
  - name: zmt
    propername: Leibniz Center for Tropical Marine Research (ZMT)
    catalogue: https://dataportal.leibniz-zmt.de/
    domain: https://www.leibniz-zmt.de/de/
    logo: https://www.leibniz-zmt.de/templates/hm_teekit_zmt_v1/images/logo/de-DE/zmt_logo_full_edge.png
    pid: https://catalogue.odis.org/view/3289
    sourcetype: sitemap
    url: https://dataportal.leibniz-zmt.de/sitemap.xml
    changefreq: monthly 
    backend: Pangaea  
    headless: false
    dateadded: 2023-11-02
    active: true