# Development config file for ODIS nodes, that drives the Dagster pipeline
# to update the ODIS graph.  Other important notes about this config file:
#  - sorted alphabetically by 'name' parameter
#  - no need to use quotes. Use the single-quoted style (') if characters 
#    such as " and \ are being used inside the string to avoid escaping them
#  - pid: should point to the ODISCat 'view' if available, such as https://catalogue.odis.org/view/689
#         or if not, use format: https://oceaninfohub.org/.well-known/org/[name]
#  - url: point to sitemap or sitegraph
#  - changefreq: how often sitemap is updated
#  - dateadded: YYYY-MM-DD (the date that JSON-LD became available, but not
#               necessarily when it was included in the ODIS graph)
#  - headless: false if JSON-LD is embedded in page, or if sitegraph
#  - cron: how often to harvest the endpoint, defaults to weekly (on Sunday)
#  - active: ready to include in ODIS
#  - if a parameter has no value, leave blank (with no quotes)
# To validate at commandline: execute the following (if the file contains valid 
# yaml, it will return nothing) :
#    python -c 'import yaml, sys; yaml.safe_load(sys.stdin)' < sources.yaml
sources:
  #
  # Belgian Marine Data Centre
  #
  - name: bmdc
    propername: Belgian Marine Data Centre (BMDC)
    catalogue: https://metadata.naturalsciences.be/geonetwork/srv/eng/catalog.search#/home
    domain: https://www.bmdc.be/
    logo: https://www.bmdc.be/NODC/images/museum.png
    pid: https://catalogue.odis.org/view/3271
    sourcetype: sitemap
    url: https://metadata.naturalsciences.be/geonetwork/srv/api/sitemap
    changefreq: daily
    backend: GeoNetwork
    headless: false
    dateadded: 2023-06-20
    cron: 0 6 * * 0
    active: true
  #
  # British Oceanographic Data Centre
  #
  - name: bodc
    propername: British Oceanographic Data Centre (BODC)
    catalogue: https://www.bodc.ac.uk/data/bodc_database/nodb/search/
    domain: https://www.bodc.ac.uk/
    logo: https://www.bodc.ac.uk/assets/img/bodc-logo-colour-white.png
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/bodc
    sourcetype: sitemap
    url: https://api.linked-systems.uk/sitemap_pap_api.xml
    changefreq: monthly
    backend: Custom
    headless: true
    dateadded: 2023-07-10
    cron: 0 7 * * 0 
    active: true
  #
  # CIOOS Atlantic
  #    
  # - name: cioosatlantic
  #   propername: CIOOS Atlantic
  #   catalogue: https://catalogue.cioosatlantic.ca/
  #   domain: https://cioosatlantic.ca
  #   logo: https://cioosatlantic.ca/wp-content/themes/cioos-siooc-wordpress-theme/img/atlantic/cioos-atlantic_EN.svg?x79655
  #   #missing ODISCat entry
  #   pid: https://oceaninfohub.org/.well-known/org/cioosatlantic
  #   sourcetype: sitemap
  #   url: https://catalogue.cioosatlantic.ca/sitemap/sitemap.xml
  #   #url: https://catalogue.cioosatlantic.ca/sitemap/sitemap-1.xml
  #   changefreq: as needed
  #   backend: CKAN  
  #   headless: false
  #   dateadded: 2022-06-04
  #   active: true
  #
  # INVEMAR Geospatial
  #
  - name: invemargeo
    propername: CHM LAC - Geospatial
    catalogue: http://portete.invemar.org.co/chm/
    domain: http://portete.invemar.org.co
    logo: http://portete.invemar.org.co/static/images/logo-web.svg
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/invemarvessels
    sourcetype: sitegraph
    url: http://portete.invemar.org.co/chm/api/oih/platformgeo?format=json
    changefreq:
    backend: INVEMAR CHM
    headless: false
    dateadded: 2023-08-22
    cron: 0 8 * * 0 
    active: true
  #
  # Marine Institute Data Catalogue
  #    
  #
  - name: marineie
    propername: Marine Institute Data Catalogue (Ireland)
    catalogue: http://data.marine.ie/geonetwork/srv/eng/catalog.search 
    domain: http://data.marine.ie
    logo: https://data.marine.ie/geonetwork/images/logos/b8055c35-285d-400a-a29f-fb308ced07c2.png?random1692727716243
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/marineie  
    sourcetype: sitemap
    url: http://data.marine.ie/geonetwork/srv/eng/portal.sitemap
    changefreq: daily
    backend: GeoNetwork
    headless: false
    dateadded: 2023-08-22
    cron: 0 9 * * 0 
    active: true
  #
  # MEDIN
  #
  - name: medin
    propername: Marine Environmental Data and Information Network (MEDIN)
    catalogue: https://portal.medin.org.uk/portal/start.php
    domain: https://medin.org.uk/
    logo: https://medin.org.uk/sites/medin/files/images/medin-portal-logo.png
    pid: https://catalogue.odis.org/view/40
    sourcetype: sitemap  
    url: https://portal.medin.org.uk/portal/sitemap.php
    changefreq: daily
    backend: MARIS
    headless: false
    dateadded: 2023-05-11
    cron: 0 10 * * 0
    active: true  
  #
  # Pacific Environment Data Portal
  #
  - name: pedp
    propername: Pacific Environment Data Portal
    catalogue: https://pacific-data.sprep.org/index.php/search
    domain: https://pacific-data.sprep.org/
    logo: https://pacific-data.sprep.org/themes/custom/inform_regional/logo.png
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/pedp
    sourcetype: sitemap
    url: https://raw.githubusercontent.com/iodepo/odis-arch/master/collection/tempHosting/data-pedp/sitemap.xml
    #url: https://pacific-data.sprep.org/sitemap.xml
    changefreq: as needed
    backend: Drupal
    headless: false
    dateadded: 2023-08-08
    cron: 0 13 * * 0 
    active: true
  #
  # POGO
  # 
  - name: pogo
    propername: Partnership for Observation of the Global Ocean
    catalogue: https://pogo-ocean.org/
    domain: https://geoblueplanet.org/
    logo: https://pogo-ocean.org/wp-content/uploads/2020/02/POGO1_long-01-768x135.png
    pid: https://catalogue.odis.org/view/3247
    sourcetype: sitemap
    url: https://pogo-ocean.org/pogo-member-sitemap.xml
    changefreq: as needed  
    backend: WordPress  
    headless: false
    dateadded: 2022-11-30
    active: false
  #
  # World Ocean Database
  # 
  - name: wod
    propername: World Ocean Database
    catalogue: https://noaa-wod-pds.s3.amazonaws.com/index.html
    domain: https://www.ncei.noaa.gov/products/world-ocean-database
    logo: https://www.ncei.noaa.gov/themes/custom/ncei/logo.svg
    pid: https://catalogue.odis.org/view/182
    sourcetype: sitemap
    url: https://raw.githubusercontent.com/iodepo/odis-arch/master/collection/tempHosting/data-wod/sitemap.xml    
    changefreq:   
    backend: AmazonS3  
    headless: false
    dateadded: 2023-09-13
    cron: 0 15 * * 0    
    active: true  
  #
  # VLIZ: Flanders Marine Institute catalogue
  #   note: VLIZ & EMODNet services were unified in late 2022 
  # - name: vliz
  #   propername: VLIZ - Flanders Marine Institute catalogue
  #   catalogue: https://emodnet.ec.europa.eu/geonetwork/srv/eng/catalog.search#/home
  #   domain: http://www.vliz.be/en 
  #   logo: ""
  #   #missing ODISCat entry
  #   pid: https://oceaninfohub.org/.well-known/org/vliz
  #   sourcetype: sitegraph
  #   url: https://raw.githubusercontent.com/iodepo/odis-arch/master/collection/tempHosting/data-vliz/vliz-simple-graph.json
  #   backend: GeoNetwork  
  #   headless: false
  #   dateadded: 2022-08-03
  #   active: false
