# Development config file for ODIS nodes, that drives the Dagster pipeline
# to update the ODIS graph.  Other important notes about this config file:
#  - sorted alphabetically by 'name' parameter
#  - no need to use quotes. Use the single-quoted style (') if characters 
#    such as " and \ are being used inside the string to avoid escaping them
#  - pid: should point to the ODISCat 'view' if available, such as https://catalogue.odis.org/view/689
#         or if not, use format: https://oceaninfohub.org/.well-known/org/[name]
#  - url: point to sitemap or sitegraph
#  - changefreq: how often sitemap is updated
#  - dateadded: YYYY-MM-DD (the date that JSON-LD became available, but not
#               necessarily when it was included in the ODIS graph)
#  - headless: false if JSON-LD is embedded in page, or if sitegraph
#  - cron: how often to harvest the endpoint, defaults to weekly (on Sunday)
#  - active: ready to include in ODIS
#  - if a parameter has no value, leave blank (with no quotes)
# To validate at commandline: execute the following (if the file contains valid 
# yaml, it will return nothing) :
#    python -c 'import yaml, sys; yaml.safe_load(sys.stdin)' < sources.yaml
sources:
  #
  # Canary Current Large Marine Ecosystem (CCLME)
  #
  - name: cclme
    propername: Canary Current Large Marine Ecosystem (CCLME)
    catalogue: https://www.fao.org/in-action/canary-current-lme/en
    domain: https://www.fao.org/in-action/canary-current-lme/en
    logo: https://www.fao.org/images/corporatelibraries/fao-logo/fao-logo-en.svg?sfvrsn=f64522b4_36
    pid: https://catalogue.odis.org/view/3276
    sourcetype: sitemap
    url: http://www.ideo-cclme.ieo.es/odis/odis_sitemap.xml
    changefreq: monthly
    backend: Custom
    headless: false
    dateadded: 2023-10-30
    cron: 0 2 * * 0
    active: true
  #
  # Indonesia National Oceanic Data Center
  #
  - name: inanodc
    propername: Indonesia National Oceanic Data Center
    catalogue: https://geonode.nodc.id
    domain: https://nodc.id
    logo: https://nodc.id/dist/img/brin.png
    pid: https://catalogue.odis.org/view/3246
    sourcetype: sitemap
    url: https://geonode.nodc.id/sitemap.xml
    #url: https://raw.githubusercontent.com/iodepo/odis-arch/master/collection/tempHosting/data-ina-nodc/ina-nodc-simple-graph.json
    changefreq: on demand
    backend: GeoNode
    headless: false
    dateadded: 2022-04-05
    active: true
    cron: 0 10 * * 0      
