# Development config file for ODIS nodes, that drives the Dagster pipeline
# to update the ODIS graph.  Other important notes about this config file:
#  - sorted alphabetically by 'name' parameter
#  - no need to use quotes. Use the single-quoted style (') if characters 
#    such as " and \ are being used inside the string to avoid escaping them
#  - pid: should point to the ODISCat 'view' if available, such as https://catalogue.odis.org/view/689
#         or if not, use format: https://oceaninfohub.org/.well-known/org/[name]
#  - url: point to sitemap or sitegraph
#  - changefreq: how often sitemap is updated
#  - dateadded: YYYY-MM-DD (the date that JSON-LD became available, but not
#               necessarily when it was included in the ODIS graph)
#  - headless: false if JSON-LD is embedded in page, or if sitegraph
#  - cron: how often to harvest the endpoint, defaults to weekly (on Sunday)
#  - active: ready to include in ODIS
#  - if a parameter has no value, leave blank (with no quotes)
# To validate at commandline: execute the following (if the file contains valid 
# yaml, it will return nothing) :
#    python -c 'import yaml, sys; yaml.safe_load(sys.stdin)' < sources.yaml
sources:
  #
  # CCHDO
  #
  - name: cchdo
    propername: CLIVAR and Carbon Hydrographic Data Office
    catalogue: https://cchdo.ucsd.edu/
    domain: https://ucsd.edu/
    logo: https://cchdo.ucsd.edu/static/svg/logo_cchdo.svg
    pid: https://catalogue.odis.org/view/3291
    sourcetype: sitemap
    url: https://cchdo.ucsd.edu/sitemap.xml
    changefreq:
    backend: ERDDAP
    headless: false
    dateadded: 2024-05-16
    cron: 0 9 * * 0 
    active: true  
  #
  # INCOIS
  #
  - name: incois
    propername: Indian National Centre for Ocean Information Services
    catalogue: https://incois.gov.in/essdp/
    domain: https://incois.gov.in/
    logo: https://incois.gov.in/essdp/images/logo.png
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/incois
    sourcetype: sitemap
    url: https://incois.gov.in/essdp/xml/sitemap.xml
    changefreq:
    backend: Custom
    headless: false
    dateadded: 2024-04-15
    cron: 0 9 * * 0 
    active: true    
  #
  # INVEMAR Geospatial
  #
  - name: invemargeo
    propername: Latin America and the Caribbean Region (LAC) Geospatial
    catalogue: https://portete.invemar.org.co/chm/
    domain: https://portete.invemar.org.co
    logo: https://www.invemar.org.co/o/invemar-actual-theme/images/logoWebINVEMAR.png
    #missing ODISCat entry
    pid: https://oceaninfohub.org/.well-known/org/invemargeo
    sourcetype: sitegraph
    url: https://portete.invemar.org.co/chm/api/oih/platformgeo?format=json
    changefreq:
    backend: INVEMAR CHM
    headless: false
    dateadded: 2023-08-22
    cron: 0 8 * * 0 
    active: true
  #
  # Marine Institute Data Catalogue
  #    
  #
  - name: marineie
    propername: Marine Institute Data Catalogue (Ireland)
    catalogue: https://data.marine.ie/geonetwork/srv/eng/catalog.search
    domain: https://data.marine.ie
    logo: https://data.marine.ie/geonetwork/images/logos/494b5d66-a774-4a7e-86f0-c860cc21331b.png
    pid: https://catalogue.odis.org/view/193
    sourcetype: sitemap
    url: https://data.marine.ie/geonetwork/srv/api/sitemap
    changefreq: daily
    backend: GeoNetwork
    headless: false
    dateadded: 2023-08-22
    cron: 0 9 * * 0 
    active: true
  #
  # NCEI Marine Microplastics Catalogue
  #    
  #
  - name: ncei
    propername: NCEI Marine Microplastics Catalogue
    catalogue: https://experience.arcgis.com/experience/b296879cc1984fda833a8acc93e31476 
    domain: https://www.ncei.noaa.gov/products/microplastics
    logo: https://www.ncei.noaa.gov/themes/custom/ncei/logo.svg
    pid: https://catalogue.odis.org/view/3295
    sourcetype: sitemap
    url: https://www.ncei.noaa.gov/sites/g/files/anmtlf171/files/2024-04/microplastics-sitemap.xml
    changefreq: monthly
    backend: ArcGIS
    headless: false
    dateadded: 2024-01-24
    cron: 0 2 * * 0 
    active: true    
  #
  # Aquatic Sciences and Fisheries Abstracts (OpenASFA)
  #
  - name: openasfa
    propername: Aquatic Sciences and Fisheries Abstracts (OpenASFA)
    catalogue: https://www.fao.org/fishery/en/openasfa
    domain: https://www.fao.org/fishery/en
    logo: https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/FAO_logo.svg/180px-FAO_logo.svg.png
    pid: https://catalogue.odis.org/view/3277
    sourcetype: sitemap
    url: https://www.fao.org/fishery/sitemap/fishery_openasfa_en.xml
    #url: https://www.fao.org/fishery/sitemap.xml
    changefreq: monthly
    backend: Custom
    headless: false
    dateadded: 2024-02-02
    cron: 0 11 * * 0 
    active: true
  #
  # UNEP Data Catalogue (also referred to as "WESR" or "GEMS Ocean")
  # 
  - name: unep
    propername: UNEP Data Catalogue
    catalogue: https://datacatalog.unep.org/app 
    domain: https://www.unep.org/
    logo: https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/UNEP_logo.svg/195px-UNEP_logo.svg.png
    pid: https://catalogue.odis.org/view/3288
    sourcetype: sitemap
    url: https://datacatalog.unep.org/en/oceans_sitemap.xml
    changefreq: monthly 
    backend: CKAN  
    headless: false
    dateadded: 2024-01-22
    active: true
  #
  # WIO Symphony
  # 
  - name: wiosymphony
    propername: WIO (Western Indian Ocean) Symphony
    catalogue: https://symphony.nairobiconvention.org/login
    domain: https://www.nairobiconvention.org/wio-symphony/
    logo: https://www.nairobiconvention.org/wp-content/uploads/2019/05/nairobic_logo.png
    pid: https://catalogue.odis.org/view/3290
    sourcetype: sitemap
    url: https://raw.githubusercontent.com/WIOSymphony/wiosym/main/metadata/sitemap.xml
    changefreq: monthly 
    backend: Custom  
    headless: false
    dateadded: 2024-01-24
    active: true