# ref: https://d2lang.com/tour/intro/
# cheat sheet: https://github.com/terrastruct/d2/blob/master/docs/assets/cheat_sheet.pdf
# Actors

Thing; Organization; ResearchOrganization

#Sitemap; Gleaner; ELT-Nabu; KnowledgeGraph
#Gleaner: {
    #shape: image
    #icon: https://gleaner.io/gleaner.png
#}


Organization -> Thing: Subclass of
 ResearchOrganization -> Organization: Subclass of
