PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema:  <https://schema.org/>

SELECT * WHERE {
    graph ?g {
      ?s rdf:type schema:Dataset .
      ?s schema:description ?description .
      ?s schema:name ?name .
      ?s schema:url ?url .
    }
}

