PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX con-inst: <http://www.ontotext.com/connectors/lucene/instance#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>
PREFIX schemaold: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT   ( COUNT(?hm) as ?count) ?wat  ?orgname ?domain
           WHERE
          {
              ?hm prov:wasAttributedTo ?wat .
              ?wat rdf:name ?orgname .
              ?wat rdfs:seeAlso ?domain
          }
          GROUP BY ?wat ?orgname ?domain

