PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <https://schema.org/>

SELECT DISTINCT (?s as ?id) ?type ?address ?txt_knowsAbout ?txt_knowsLanguage
WHERE {
    graph ?g {
        BIND(schema:Person AS ?type)
        ?s rdf:type ?type .
        OPTIONAL { ?s schema:address ?address . }
        OPTIONAL { ?s schema:knowsAbout ?txt_knowsAbout . }
        OPTIONAL { ?s schema:knowsLanguage ?txt_knowsLanguage . }
     }
}
