PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <https://schema.org/>


SELECT DISTINCT (?s as ?id)  ?type
WHERE {
    graph ?g {
        ?s rdf:type ?type .
      FILTER (?type IN (schema:ResearchProject, schema:Project, schema:Organization,
                           schema:Dataset, schema:CreativeWork, schema:Person, schema:Map, schema:Course,
                           schema:CourseInstance, schema:Event, schema:Vehicle)
      )
        FILTER(!regex(str(?s), "genid"))
    }
 }
