PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <https://schema.org/>

SELECT  ?name ?url ?description ?s
WHERE {
    graph ?g {
        ?s schema:variableMeasured ?vm .
        ?vm ?p ?o
        OPTIONAL { ?vm schema:name ?name . }
        OPTIONAL { ?vm schema:url ?url . }
        OPTIONAL { ?vm schema:description ?description . }
    }
}
