PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <https://schema.org/>

SELECT DISTINCT ?s ?type ?name ?address ?description ?courseName ?location
WHERE {
    graph ?g {
        BIND(schema:Organization AS ?type)
        ?s rdf:type ?type .
        OPTIONAL { ?s schema:name ?name . }
        OPTIONAL { ?s schema:address ?address . }
        OPTIONAL { ?s schema:description ?description . }
        OPTIONAL {
            ?s schema:hasCourseInstance ?hasCourseInstance .
            ?hasCourseInstance schema:name ?courseName
        }
        OPTIONAL { ?s schema:location ?location . }
    }
}
