direction: right

classes: {
coreclass: {
    width: 200
               style: {
                     stroke-width: 0
                     font-size: 18
                    fill: lightgreen
                    shadow: true
                    border-radius: 5
               }
      }
      actionclass: {
    width: 250
               style: {
                     stroke-width: 1
                     font-size: 18
                     fill: lightblue
                    shadow: false
                    border-radius: 0
               }
      }
propclass: {
    width: 250
               style: {
                     stroke-width: 1
                     font-size: 18
                     fill: lightyellow
                    shadow: false
                    border-radius: 0
               }
      }
prodclass: {
    width: 250
               style: {
                     stroke-width: 1
                     font-size: 18
                     fill: honeydew
                    shadow: false
                    border-radius: 0
               }
      }
}