version: '3'

# ${MINIO_ACCESS_KEY}  
# ${MINIO_SECRET_KEY}
# ${GLEANER_OBJECTS}
# ${GLEANER_GRAPH}

services:
  triplestore:
    image: nawer/blazegraph 
    environment:
      JAVA_XMS: 2g
      JAVA_XMX: 8g
      JAVA_OPTS: -Xmx6g -Xms2g --XX:+UseG1GC
    ports:
      - 9999:9999
    volumes:
      - ${GLEANER_GRAPH}:/var/lib/blazegraph
    networks:
      - traefik_default

  s3system:
    image: minio/minio:latest
    ports:
      - 9000:9000
    volumes:
      - ${GLEANER_OBJECTS}:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    networks:
      - traefik_default
    command: ["server", "/data"]

  headless:
    image: chromedp/headless-shell:latest
    labels:
      - "traefik.backend=headlesschrome"
      - "traefik.port=9222"
    ports:
      - 9222:9222
    environment:
     - SERVICE_PORTS=9222
    networks:
      - traefik_default    

networks:
  traefik_default:
