direction:right


pub: "Publisher" {

    small jerry: "" {
        shape: image
        icon: profile.png
        width: 100
        height: 100
    }

    note: |md
        This is a way to push this wider

        * one
        * two
        * three
        * four
    |

}



agr: "Agregator" {

    small jerry: "" {
        shape: image
        icon: profile.png
        width: 100
        height: 100
    }

    note: |md
        This is a way to push this wider
    |

}



user: "Users" {

    small jerry: "" {
        shape: image
        icon: profile.png
        width: 100
        height: 100
    }

    note: |md
        This is a way to push this wider
    |

      width: 200
  height: 200

}


pub -> agr -> user
