PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <https://schema.org/>


SELECT (COUNT(?type) as ?count) ?type
WHERE {
    graph ?g {
        ?s rdf:type ?type
        FILTER (?type IN
                (schema:ResearchProject, schema:Project, schema:Organization, schema:Dataset,
                    schema:CreativeWork, schema:Person, schema:Map, schema:Course,
                    schema:CourseInstance, schema:Event, schema:Vehicle)
        )
    }
}
GROUP BY ?type
ORDER BY DESC(?count)
