direction: right

oih: Ocean InfoHub

web: Web Assets
web.book: The Book \n (Publication)
web.dashboard: OIH status dashboard
web.search: Search \n (Web User Interface)
web.sp: SPARQL endpoint
web.rg:  Graph Releases \n (Data Publication)

aa: Architecture Assets
aa.adr:  Decision Records
aa.av: Archicture Validation \n sitemaps, etc
aa.reports: Validation reports

oih -> aa.av
oih -> aa.adr

sa: Semantic Assets
sa.dg:  Profiles
sa.sg:  Validation Graphs (SHACL)
sa.js:  JSON Schema
sa.fr:  Graph Frames
sa.rs:  SPARQL queries


oih -> web.search
oih -> web.dashboard
oih -> web.sp
oih -> web.book
oih -> web.rg
oih -> sa.dg
oih -> sa.sg
oih -> sa.js
oih -> sa.fr
oih -> sa.rs

sa.sg -> aa.reports

ce: Community engagement {
  style: {
    fill: deepskyblue
  }
}
ue: User engagement {
  style: {
    fill: deepskyblue
  }
}

web.search <- ue
web.sp <- ue
web.rg <- ue

web.dashboard <- ce
sa <- ce: Community contributions \n to development
aa <- ce: Community contributions \n to development
# sa.reports <- ce : Community feedback loop \n on validation
web.book <- ce
