name: ODIS config builder

on:
    workflow_dispatch:
    schedule:
        - cron: "0 6 * * *"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m venv venv
                  pip install -r workflows/actions/odiscat/requirements.txt

            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

            - name: Run Python script
              run: |
                  python workflows/actions/odiscat/catconfig.py https://catalogue.odis.org/sitemapIndex.xml

            - name: Add new files to Git
              run: |
                  git config --global user.email "github-actions@example.com"
                  git config --global user.name "GitHub Actions"
                  git add workflows/actions/odiscat/gleanerconfig.yaml
                  git commit -m "Latest ODIS catalog config file built"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
