#schedule a book publish weekly, on Sundays, by merging
# master into the publication branch (which will then trigger the
# deploy-book.yml action)

name: "Weekly book publish"

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Git config
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"    
    
    - name: Merge master into publication
      uses: actions/checkout@v4
      run: |      
          git fetch --unshallow
          git checkout publication
          git pull
          git merge --no-ff master -m "Auto-merge master back to publication"
          git push

